name: 'Email Notification Workflow'

on: workflow_dispatch

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Convert Notebook"
        run: |
          pip install jupyter
          pip install -r requirements.txt
          jupyter nbconvert --to html --execute analysis.ipynb --no-input
          ## run jupyter and convert to html
      - name: 'Send Mail'
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          username: elizabethdbagley2@gmail.com
          password: ${{secrets.MAIL_DATA_DAYS}}
          subject: Github Actions Test
          to: elibagley2@gmail.com
          from: example@example.com
          html_body: file://analysis.html
